# Introducción a Numpy


Acometer un proyecto de Machine Learning o IA requiere un manejo intensivo y eficaz de cálculo matricial, y NumPy pone a nuestra disposición toda esa potencia. La libraría dispone de un montón de herramientas y capacidades.

Vamos a crear una matriz:

In [3]:
#Importa la libreria
import numpy as np

#Se crea una matriz de dimensión 2x4
matrix1 = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8]])
print (matrix1)

[[1 2 3 4]
 [5 6 7 8]]


Existen otras tres funciones que nos facilitan la creación de matrices: **`zeros()`** crea una matriz inicializada con el valor 0, **`ones()`** hace lo mismo pero con todos sus valores a 1. Finalmente, **`eye()`** crea la matriz identidad del tamaño que especifiquemos como parámetro

In [25]:
#Zeros 
zeros = np.zeros([2,3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
#Ones
ones = np.ones([3,2])
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [28]:
#Eye
eye = np.eye(4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Podemo acceder a valores concretos de la matriz o a porciones completas

In [4]:
matrix1 = np.matrix('1,2,3;4,5,6;7,8,9')
print(matrix1, '\n')

#Estamos accediendo a la primera fila(fila 0) de la matriz 
print('Accede a valor concreto\n',matrix1[0],'\n')

#Si se quiere acceder a un sólo elemento
print('Accede al elemento: \n', matrix1[0,1])

#Se aplica de igual forma a las columnas
print('Imprime columna especficca\n',matrix1[0:3,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Accede a valor concreto
 [[1 2 3]] 

Accede al elemento: 
 2
Imprime columna especficca
 [[1]
 [4]
 [7]]


Las funciones **`size()`** y **`shape()`** nos devuelven el número de elementos y la dimensión de la matriz respectivamente. 

Otra información que se puede obtener es el valor **máximo**, el **minimo** y la **media** de los valores de la matriz

In [12]:
print('Imprime número de elementos: \n',matrix1.size)

print('Imprime dimensión de la matriz: \n', matrix1.shape)

print('valor máximo: \n', matrix1.max())

print('Valor minimo: \n', matrix1.min())

print('Imprime Media: \n', matrix1.mean())

Imprime número de elementos: 
 4
Imprime dimensión de la matriz: 
 (2, 2)
valor máximo: 
 4
Valor minimo: 
 1
Imprime Media: 
 2.5


También se pueden modificar los elementos:

In [15]:
matrix1 = np.matrix('1 2; 3 4 ')
print('Se renombra elementos de la matriz: \n',matrix1)

matrix1[1, 0] = 10
print('Se reemplaza elementos de la matriz: \n', matrix1)

matrix1[0] = [6,7]
print('Se sustituye una fila entera de la matriz: \n',matrix1)

Se renombra elementos de la matriz: 
 [[1 2]
 [3 4]]
Se reemplaza elementos de la matriz: 
 [[ 1  2]
 [10  4]]
Se sustituye una fila entera de la matriz: 
 [[ 6  7]
 [10  4]]


Otra función útil es **``flatten()`**, que convierte la matriz en un array de una dimensión con todos los elementos de la matriz

In [17]:
print('Convierte matriz en un array de una sola dimensión: \n',matrix1.flatten())

Convierte matriz en un array de una sola dimensión: 
 [[ 6  7 10  4]]


Operaciones matemáticas, en este caso la matriz traspuesta.

In [18]:
print('Matriz traspuesta: \n', matrix1.T)

Matriz traspuesta: 
 [[ 6 10]
 [ 7  4]]


Sobre las matrices se pueden aplicar las operaciones matemáticas básicas, tanto entre matrices como entre una matriz y un escalar. Los siguientes ejemplos ilustran la suma de una matriz y un escalar y la suma entre dos matrices.

In [22]:
matrix1 = np.matrix('1 2; 3 4')
matrix2 = np.matrix('5 6; 7 8')
print ('Suma de una matriz y un escalar: \n',matrix1 + 2)

print('Suma entre dos matrices: \n', matrix1 + matrix2)

Suma de una matriz y un escalar: 
 [[3 4]
 [5 6]]
Suma entre dos matrices: 
 [[ 6  8]
 [10 12]]
